// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// qqconf
NumericMatrix qqconf(const int n, int conf_points, double conf_alpha);
RcppExport SEXP _gwasplot_qqconf(SEXP nSEXP, SEXP conf_pointsSEXP, SEXP conf_alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type conf_points(conf_pointsSEXP);
    Rcpp::traits::input_parameter< double >::type conf_alpha(conf_alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(qqconf(n, conf_points, conf_alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gwasplot_qqconf", (DL_FUNC) &_gwasplot_qqconf, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_gwasplot(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
